ntut-open-source-club/practical-tools-for-simple-design

CMakeLists.txt
include/App.hpp
include/Core/Context.hpp
include/Core/DebugMessageCallback.hpp
include/Core/IndexBuffer.hpp
include/Core/Program.hpp
include/Core/Shader.hpp
include/Core/UniformBuffer.hpp
include/Core/VertexArray.hpp
include/Core/VertexBuffer.hpp
include/Triangle.hpp
include/Util/Input.hpp
include/Util/Keycode.hpp
include/Util/LoadTextFile.hpp
include/Util/Logger.hpp
include/Util/Time.hpp
include/config.hpp
include/pch.hpp
src/App.cpp
src/Core/Context.cpp
src/Core/DebugMessageCallback.cpp
src/Core/Program.cpp
src/Core/Shader.cpp
src/Triangle.cpp
src/Util/Input.cpp
src/main.cpp

No functional changes, only setup precompiled headers to improve compile times and refactored some code to provide a better base to build on.

Added PCH and Refactor

---

src/App.cpp

fix typo _from https://github.com/NOOBDY/practical-tools-for-simple-design/commit/3665f83b1a855987906858522079a9c6cf6c0fd9 in #7_

Keycode -> Util::Keycode

---

include/Util/BGM.hpp
include/Util/SFX.hpp

Meet #11 's requirement

---

include/Util/Input.hpp
src/App.cpp
src/Core/Context.cpp
src/Util/Input.cpp

1. [x] Make methods static.
2. [x] Add documents to things.
3. [x] Add SetCursorPosition method.

Refactor Util::Input class

---

CMakeLists.txt

added PTSD_ENALBE_PCH cmake flag to conditionally enable pch

---

src/Core/Texture.cpp
src/Util/Text.cpp

Fix: #57
Work on my machine. Thanks @NOOBDY help me to fix the bug.
Hard to take snapshot btw >:(

FIx Color Channel Issue in macOS

---

include/Core/UniformBuffer.hpp
include/Core/UniformBuffer.inl
include/Util/TransformUtils.hpp
src/Util/Image.cpp
src/Util/Text.cpp
src/Util/TransformUtils.cpp

Fix #54 
- Add `glBindBufferBase(GL_UNIFORM_BUFFER, m_Binding, m_BufferId);`
- Refactor

fix uniform buffer data not apply issue

---

src/Util/Input.cpp

#52 but merge into main

---

.github/docs/Code-Styles-and-Guidelines.md
CONTRIBUTING.md

📝 Code Styles and Guidelines

---

include/Util/Logger.hpp
include/pch.hpp

the code can be
```cpp
glm::vec2 v(2, 3);
LOG_DEBUG("{}", glm::to_string(v));
```

added string cast

---

.clang-format
include/Util/BGM.hpp
include/Util/Color.hpp
include/Util/GameObject.hpp
include/Util/Image.hpp
include/Util/Input.hpp
include/Util/Logger.hpp
include/Util/Root.hpp
include/Util/SFX.hpp
include/Util/Text.hpp
include/Util/Time.hpp
include/Util/Transform.hpp
include/Util/TransformUtils.hpp
src/Util/TransformUtils.cpp

Add and fix Util doc

---

.github/workflows/docs.yml

Preview the page [here](https://noobdy.github.io/practical-tools-for-simple-design/)

added docs github actions

---

include/Util/Input.hpp
src/App.cpp
src/Util/Input.cpp

Enhance: Make Util::Input detect if mouse button up.

---

src/Util/Root.cpp

- fix #120 by sort the render order of image

z-index sort

---

include/Util/Input.hpp
include/Util/Keycode.hpp
src/App.cpp
src/Util/Input.cpp

Resolves #117
Test with `App::Update()` if you feel like.

Edge detections for mouse button and key inputs.

---

include/Util/Animation.hpp

Remove Reset function in animation.

---

include/Util/Text.hpp
src/Util/Text.cpp

temporarily deals with #164, the issue will remain open until the root cause is resolved

remove store implementation from Util::Text

---

CMakeLists.txt

fix small bug

---

src/Util/GameObject.cpp

check if m_Drawable is nullptr

---

include/Util/MissingTexture.hpp
src/Util/Image.cpp

Fix: Undefined Reference Missing font texture

---

include/Core/Texture.hpp
include/Util/Image.hpp
include/Util/Text.hpp
src/Core/Texture.cpp
src/Util/Image.cpp
src/Util/Text.cpp

added anti-aliasing support and some documentation
